@Host = https://localhost:7159/api/accounts


### Register
POST {{Host}}/register
Accept: application/json
Content-Type: application/json

{
    "emailAddress" : "email@example.com",
    "password" : "password",
    "confirmPassword" : "password"
}

###
