@Host = https://localhost:7159/api/v1/auth


### Register
POST {{Host}}/register
Accept: application/json
Content-Type: application/json

{
    "emailAddress" : "mrsang005@example.com",
    "password" : "StrongPass123",
    "passwordConfirmation" : "StrongPass123"
}

### Login user
POST {{Host}}/login
Accept: application/json
Content-Type: application/json

{
    "emailAddress" : "mrsteve@example.com",
    "password" : "password123"
}

