@Host = https://account-api.internal.blackcliff-ca28c804.southeastasia.azurecontainerapps.io/api/v1/auth


### Register
POST {{Host}}/register
Accept: application/json
Content-Type: application/json

{
    "emailAddress" : "mrsang004@example.com",
    "password" : "password",
    "confirmPassword" : "password"
}

### Login user
POST {{Host}}/login
Accept: application/json
Content-Type: application/json

{
    "emailAddress" : "mrsteve@example.com",
    "password" : "password"
}

